<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CncLoader.Core\CncLoader.Core.csproj" />
    <ProjectReference Include="..\CncLoader.Common\CncLoader.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <!-- 嵌入字体（随程序打包，不依赖系统已装） -->
  <ItemGroup>
    <Resource Include="Assets\Fonts\*.ttf" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
