-- 现有库：为 MAS_AUTO_WORKLINE_AGV 增加 RCS 连接配置列（可重复执行：已存在则跳过）
-- 用法：mysql -u root -p cnc_auto < docs/sql/migrate_workline_agv_rcs.sql

USE cnc_auto;

SET @db := DATABASE();

-- RCS_BASE_URL
SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA=@db AND TABLE_NAME='MAS_AUTO_WORKLINE_AGV' AND COLUMN_NAME='RCS_BASE_URL');
SET @sql := IF(@exists=0,
  'ALTER TABLE MAS_AUTO_WORKLINE_AGV ADD COLUMN RCS_BASE_URL VARCHAR(200) NULL COMMENT ''RCS出站基址'' AFTER AGV_READ_JSON',
  'SELECT ''RCS_BASE_URL already exists''');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA=@db AND TABLE_NAME='MAS_AUTO_WORKLINE_AGV' AND COLUMN_NAME='RCS_CLIENT_CODE');
SET @sql := IF(@exists=0,
  'ALTER TABLE MAS_AUTO_WORKLINE_AGV ADD COLUMN RCS_CLIENT_CODE VARCHAR(50) NULL COMMENT ''clientCode'' AFTER RCS_BASE_URL',
  'SELECT ''RCS_CLIENT_CODE already exists''');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA=@db AND TABLE_NAME='MAS_AUTO_WORKLINE_AGV' AND COLUMN_NAME='RCS_CALLBACK_HOST');
SET @sql := IF(@exists=0,
  'ALTER TABLE MAS_AUTO_WORKLINE_AGV ADD COLUMN RCS_CALLBACK_HOST VARCHAR(50) NULL COMMENT ''回调监听IP'' AFTER RCS_CLIENT_CODE',
  'SELECT ''RCS_CALLBACK_HOST already exists''');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA=@db AND TABLE_NAME='MAS_AUTO_WORKLINE_AGV' AND COLUMN_NAME='RCS_CALLBACK_PORT');
SET @sql := IF(@exists=0,
  'ALTER TABLE MAS_AUTO_WORKLINE_AGV ADD COLUMN RCS_CALLBACK_PORT INT NULL COMMENT ''回调监听端口'' AFTER RCS_CALLBACK_HOST',
  'SELECT ''RCS_CALLBACK_PORT already exists''');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA=@db AND TABLE_NAME='MAS_AUTO_WORKLINE_AGV' AND COLUMN_NAME='RCS_TIMEOUT_MS');
SET @sql := IF(@exists=0,
  'ALTER TABLE MAS_AUTO_WORKLINE_AGV ADD COLUMN RCS_TIMEOUT_MS INT NULL COMMENT ''出站超时毫秒'' AFTER RCS_CALLBACK_PORT',
  'SELECT ''RCS_TIMEOUT_MS already exists''');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA=@db AND TABLE_NAME='MAS_AUTO_WORKLINE_AGV' AND COLUMN_NAME='RCS_MAX_RETRIES');
SET @sql := IF(@exists=0,
  'ALTER TABLE MAS_AUTO_WORKLINE_AGV ADD COLUMN RCS_MAX_RETRIES INT NULL COMMENT ''网络重试次数'' AFTER RCS_TIMEOUT_MS',
  'SELECT ''RCS_MAX_RETRIES already exists''');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @exists := (SELECT COUNT(*) FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA=@db AND TABLE_NAME='MAS_AUTO_WORKLINE_AGV' AND COLUMN_NAME='RCS_POLL_INTERVAL_MS');
SET @sql := IF(@exists=0,
  'ALTER TABLE MAS_AUTO_WORKLINE_AGV ADD COLUMN RCS_POLL_INTERVAL_MS INT NULL COMMENT ''兜底轮询间隔毫秒'' AFTER RCS_MAX_RETRIES',
  'SELECT ''RCS_POLL_INTERVAL_MS already exists''');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
