-- 还原：恢复「一机一逻辑 PLC」三行配置（撤回 migrate_plc_single_fins）
-- 现场共物理 PLC 时三行 IP/端口可相同。幂等。执行前请停客户端。

USE cnc_auto;

-- 1) 恢复/更新三台逻辑 PLC（FINS 同 IP 示例；演示模拟器仍按 PLC_ID 分端口）
INSERT INTO MAS_AUTO_WORKLINE_PLC
  (PLC_ID, PLC_NAME, PLC_CONNECT_TYPE, PLC_COMPUTER_IP, PLC_COMPUTER_PORT, PLC_READ_WAY, STATE, AUTHOR)
SELECT 1, '内长宽PLC', '客户端', '192.168.250.1', 9600, 'FINS', '0', 'revert'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM MAS_AUTO_WORKLINE_PLC WHERE PLC_ID = 1);

INSERT INTO MAS_AUTO_WORKLINE_PLC
  (PLC_ID, PLC_NAME, PLC_CONNECT_TYPE, PLC_COMPUTER_IP, PLC_COMPUTER_PORT, PLC_READ_WAY, STATE, AUTHOR)
SELECT 2, '平面度PLC', '客户端', '192.168.250.1', 9600, 'FINS', '0', 'revert'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM MAS_AUTO_WORKLINE_PLC WHERE PLC_ID = 2);

INSERT INTO MAS_AUTO_WORKLINE_PLC
  (PLC_ID, PLC_NAME, PLC_CONNECT_TYPE, PLC_COMPUTER_IP, PLC_COMPUTER_PORT, PLC_READ_WAY, STATE, AUTHOR)
SELECT 3, 'A基准PLC', '客户端', '192.168.250.1', 9600, 'FINS', '0', 'revert'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM MAS_AUTO_WORKLINE_PLC WHERE PLC_ID = 3);

UPDATE MAS_AUTO_WORKLINE_PLC SET
  PLC_NAME='内长宽PLC', PLC_COMPUTER_IP='192.168.250.1', PLC_COMPUTER_PORT=9600,
  PLC_READ_WAY='FINS', STATE='0', AUTHOR='revert', UPDATETIME=NOW()
WHERE PLC_ID=1;

UPDATE MAS_AUTO_WORKLINE_PLC SET
  PLC_NAME='平面度PLC', PLC_COMPUTER_IP='192.168.250.1', PLC_COMPUTER_PORT=9600,
  PLC_READ_WAY='FINS', STATE='0', AUTHOR='revert', UPDATETIME=NOW()
WHERE PLC_ID=2;

UPDATE MAS_AUTO_WORKLINE_PLC SET
  PLC_NAME='A基准PLC', PLC_COMPUTER_IP='192.168.250.1', PLC_COMPUTER_PORT=9600,
  PLC_READ_WAY='FINS', STATE='0', AUTHOR='revert', UPDATETIME=NOW()
WHERE PLC_ID=3;

-- 2) 机台恢复一机一 PLC
UPDATE MAS_AUTO_WORKLINE_EQUIMENT SET PLC_ID=1, AUTHOR='revert', UPDATETIME=NOW() WHERE ID1=1 AND STATE='0';
UPDATE MAS_AUTO_WORKLINE_EQUIMENT SET PLC_ID=2, AUTHOR='revert', UPDATETIME=NOW() WHERE ID1=2 AND STATE='0';
UPDATE MAS_AUTO_WORKLINE_EQUIMENT SET PLC_ID=3, AUTHOR='revert', UPDATETIME=NOW() WHERE ID1=3 AND STATE='0';

-- 3) 点位按机台归回对应 PLC_ID（寄存器区不变）
UPDATE MAS_AUTO_PLC_POINT SET PLC_ID=1, UPDATETIME=NOW() WHERE EQUIMENT_ID=1 AND STATE='0';
UPDATE MAS_AUTO_PLC_POINT SET PLC_ID=2, UPDATETIME=NOW() WHERE EQUIMENT_ID=2 AND STATE='0';
UPDATE MAS_AUTO_PLC_POINT SET PLC_ID=3, UPDATETIME=NOW() WHERE EQUIMENT_ID=3 AND STATE='0';
