-- 演示态料架还原：上料架101(FRAME_ID=1) 按 10 层×左右 2 位补满（101101/101102 … 101191/101192）。
-- 其余料架清空。可重复执行；不动机台/点位/任务等其它表。
-- 假定已跑 update_field_location_codes.sql（上料架已是 20 槽）。禁止在生产库执行。

USE cnc_auto;

UPDATE MAS_AUTO_FRAME_SLOT
SET SLOT_STATE = '0',
    ELECTRODE_ID = NULL,
    BIND_SOURCE = NULL,
    BIND_TIME = NULL,
    REMARK = NULL
WHERE FRAME_ID <> 1;

UPDATE MAS_AUTO_FRAME_SLOT s
JOIN (
  SELECT (l.n - 1) * 2 + p.n AS SLOT_NO,
         CONCAT('101', 9 + l.n, p.n) AS ELECTRODE_ID
  FROM (
    SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
    UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
  ) l
  CROSS JOIN (SELECT 1 n UNION ALL SELECT 2) p
) v ON v.SLOT_NO = s.SLOT_NO
SET s.SLOT_STATE = '1',
    s.ELECTRODE_ID = v.ELECTRODE_ID,
    s.BIND_SOURCE = 'MANUAL',
    s.BIND_TIME = NOW(),
    s.REMARK = NULL
WHERE s.FRAME_ID = 1;

INSERT INTO MAS_AUTO_FRAME_SLOT
  (FRAME_ID, SLOT_NO, LAYER_NO, POS_IN_LAYER, SLOT_STATE, ELECTRODE_ID, BIND_SOURCE, BIND_TIME)
SELECT 1, (l.n - 1) * 2 + p.n, l.n, p.n, '1', CONCAT('101', 9 + l.n, p.n), 'MANUAL', NOW()
FROM (
  SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
  UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
) l
CROSS JOIN (SELECT 1 n UNION ALL SELECT 2) p
LEFT JOIN MAS_AUTO_FRAME_SLOT s
  ON s.FRAME_ID = 1 AND s.SLOT_NO = (l.n - 1) * 2 + p.n
WHERE s.ID1 IS NULL;

SELECT FRAME_ID, SLOT_STATE, COUNT(*) c
FROM MAS_AUTO_FRAME_SLOT
GROUP BY FRAME_ID, SLOT_STATE
ORDER BY FRAME_ID, SLOT_STATE;

SELECT SLOT_NO, LAYER_NO, POS_IN_LAYER, SLOT_STATE, ELECTRODE_ID
FROM MAS_AUTO_FRAME_SLOT
WHERE FRAME_ID = 1
ORDER BY SLOT_NO;
