-- 演示态料架还原：上料总架(FRAME_ID=1) 补满 EL-001..EL-010，其余料架清空。
-- 可重复执行；不动机台/点位/任务等其它表。

USE cnc_auto;

-- 1) 非上料架全部置空
UPDATE MAS_AUTO_FRAME_SLOT
SET SLOT_STATE = '0',
    ELECTRODE_ID = NULL,
    BIND_SOURCE = NULL,
    BIND_TIME = NULL,
    REMARK = NULL
WHERE FRAME_ID <> 1;

-- 2) 上料架 1..10 补满
UPDATE MAS_AUTO_FRAME_SLOT
SET SLOT_STATE = '1',
    ELECTRODE_ID = CASE SLOT_NO
      WHEN 1 THEN 'EL-001'
      WHEN 2 THEN 'EL-002'
      WHEN 3 THEN 'EL-003'
      WHEN 4 THEN 'EL-004'
      WHEN 5 THEN 'EL-005'
      WHEN 6 THEN 'EL-006'
      WHEN 7 THEN 'EL-007'
      WHEN 8 THEN 'EL-008'
      WHEN 9 THEN 'EL-009'
      WHEN 10 THEN 'EL-010'
    END,
    BIND_SOURCE = 'MANUAL',
    BIND_TIME = NOW(),
    REMARK = NULL
WHERE FRAME_ID = 1 AND SLOT_NO BETWEEN 1 AND 10;

-- 若上料架槽位行缺失则插入（首次残缺库兜底）
INSERT INTO MAS_AUTO_FRAME_SLOT
  (FRAME_ID, SLOT_NO, LAYER_NO, POS_IN_LAYER, SLOT_STATE, ELECTRODE_ID, BIND_SOURCE, BIND_TIME)
SELECT v.FRAME_ID, v.SLOT_NO, v.LAYER_NO, v.POS_IN_LAYER, v.SLOT_STATE, v.ELECTRODE_ID, v.BIND_SOURCE, v.BIND_TIME
FROM (
  SELECT 1 FRAME_ID, 1 SLOT_NO, 1 LAYER_NO, 1 POS_IN_LAYER, '1' SLOT_STATE, 'EL-001' ELECTRODE_ID, 'MANUAL' BIND_SOURCE, NOW() BIND_TIME
  UNION ALL SELECT 1, 2, 1, 2, '1', 'EL-002', 'MANUAL', NOW()
  UNION ALL SELECT 1, 3, 1, 3, '1', 'EL-003', 'MANUAL', NOW()
  UNION ALL SELECT 1, 4, 1, 4, '1', 'EL-004', 'MANUAL', NOW()
  UNION ALL SELECT 1, 5, 1, 5, '1', 'EL-005', 'MANUAL', NOW()
  UNION ALL SELECT 1, 6, 2, 1, '1', 'EL-006', 'MANUAL', NOW()
  UNION ALL SELECT 1, 7, 2, 2, '1', 'EL-007', 'MANUAL', NOW()
  UNION ALL SELECT 1, 8, 2, 3, '1', 'EL-008', 'MANUAL', NOW()
  UNION ALL SELECT 1, 9, 2, 4, '1', 'EL-009', 'MANUAL', NOW()
  UNION ALL SELECT 1, 10, 2, 5, '1', 'EL-010', 'MANUAL', NOW()
) v
LEFT JOIN MAS_AUTO_FRAME_SLOT s
  ON s.FRAME_ID = v.FRAME_ID AND s.SLOT_NO = v.SLOT_NO
WHERE s.ID1 IS NULL;

-- 汇总：按架看占用/空闲
SELECT FRAME_ID, SLOT_STATE, COUNT(*) c
FROM MAS_AUTO_FRAME_SLOT
GROUP BY FRAME_ID, SLOT_STATE
ORDER BY FRAME_ID, SLOT_STATE;

SELECT SLOT_NO, LAYER_NO, POS_IN_LAYER, SLOT_STATE, ELECTRODE_ID
FROM MAS_AUTO_FRAME_SLOT
WHERE FRAME_ID = 1
ORDER BY SLOT_NO;
