-- 料架 cell 改为：货架码 + 层编码（第1层=10、第2层=11…）+ 层内位 1 位。
-- 例：上料 L1=101101/101102、L2=101111/101112、L10=101191/101192；中转 301/302、下料 303、NG 401 同规则。
-- 不改 shelf / 加工位 / 区域；不改货架前缀。可重复执行。禁止在生产库未备份时执行。执行后须重启客户端。

USE cnc_auto;

UPDATE MAS_AUTO_LOCATION_MAP
SET STATE='1'
WHERE STATE='0' AND LOC_TYPE='FRAME' AND RCS_TYPE='cell'
  AND FRAME_ID IN (1, 2, 3, 91, 92);

INSERT INTO MAS_AUTO_LOCATION_MAP (LOC_TYPE, FRAME_ID, LOC_NAME, RCS_CODE, RCS_TYPE, STATE, AUTHOR)
SELECT 'FRAME', f.id, CONCAT('L', l.n, 'P', p.n), CONCAT(f.code, 9 + l.n, p.n), 'cell', '0', 'system'
FROM (
  SELECT 1 AS id, '101' AS code
  UNION ALL SELECT 2, '301'
  UNION ALL SELECT 3, '303'
  UNION ALL SELECT 91, '401'
  UNION ALL SELECT 92, '302'
) f
CROSS JOIN (
  SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
  UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
) l
CROSS JOIN (SELECT 1 n UNION ALL SELECT 2) p
WHERE NOT EXISTS (
  SELECT 1 FROM MAS_AUTO_LOCATION_MAP m
  WHERE m.STATE='0' AND m.RCS_CODE = CONCAT(f.code, 9 + l.n, p.n)
);

SELECT FRAME_ID, RCS_CODE, LOC_NAME
FROM MAS_AUTO_LOCATION_MAP
WHERE STATE='0' AND LOC_TYPE='FRAME' AND RCS_TYPE='cell'
  AND FRAME_ID IN (1, 3)
ORDER BY FRAME_ID, LOC_NAME;

SELECT FRAME_ID, COUNT(*) c
FROM MAS_AUTO_LOCATION_MAP
WHERE STATE='0' AND LOC_TYPE='FRAME' AND RCS_TYPE='cell'
GROUP BY FRAME_ID
ORDER BY FRAME_ID;
