-- 已有库切换到现场搬运编码（不 DROP 整库）。
-- 料架布局：10 层 × 左右 2 位。
-- cell = 货架码 + 层号（不补零）+ 层内位 2 位：
--   上料 101：L1=101101/101102 … L10=1011001/1011002
--   中转 301/302、下料 303、NG 401：同规则
-- 会重建全部料架槽位（含预记）。可重复执行。禁止在生产库未备份时执行。执行后须重启客户端。

USE cnc_auto;

UPDATE MAS_AUTO_FRAME SET FRAME_NAME='上料架101', FRAME_CODE='101', FRAME_IDENTIFY_CODE='101',
  LAYER_TOTAL=10, SLOTS_PER_LAYER=2, SLOT_TOTAL=20 WHERE ID1=1;
UPDATE MAS_AUTO_FRAME SET FRAME_NAME='中转架301', FRAME_CODE='301', FRAME_IDENTIFY_CODE='301',
  LAYER_TOTAL=10, SLOTS_PER_LAYER=2, SLOT_TOTAL=20 WHERE ID1=2;
UPDATE MAS_AUTO_FRAME SET FRAME_NAME='下料总架303', FRAME_CODE='303', FRAME_IDENTIFY_CODE='303',
  LAYER_TOTAL=10, SLOTS_PER_LAYER=2, SLOT_TOTAL=20 WHERE ID1=3;
UPDATE MAS_AUTO_FRAME SET FRAME_NAME='NG架401', FRAME_CODE='401', FRAME_IDENTIFY_CODE='401',
  LAYER_TOTAL=10, SLOTS_PER_LAYER=2, SLOT_TOTAL=20 WHERE ID1=91;
UPDATE MAS_AUTO_FRAME SET FRAME_NAME='中转架302', FRAME_CODE='302', FRAME_IDENTIFY_CODE='302',
  LAYER_TOTAL=10, SLOTS_PER_LAYER=2, SLOT_TOTAL=20 WHERE ID1=92;

UPDATE MAS_AUTO_LOCATION_MAP SET STATE='1'
WHERE STATE='0' AND (
  (LOC_TYPE='AREA' AND LOC_NAME IN ('LOAD_AREA', 'UNLOAD_AREA'))
  OR RCS_CODE IN ('651001','651002','651003','651091','651092','653002','653091','653092')
);

-- 作废旧 cell（2×5 / 2×6 多出的位，如 101103、301106）
UPDATE MAS_AUTO_LOCATION_MAP m
LEFT JOIN (
  SELECT CONCAT(f.code, l.n, LPAD(p.n, 2, '0')) AS code
  FROM (
    SELECT '101' AS code UNION ALL SELECT '301' UNION ALL SELECT '302'
    UNION ALL SELECT '303' UNION ALL SELECT '401'
  ) f
  CROSS JOIN (
    SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
    UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
  ) l
  CROSS JOIN (SELECT 1 n UNION ALL SELECT 2) p
) keep ON keep.code = m.RCS_CODE
SET m.STATE='1'
WHERE m.STATE='0' AND m.LOC_TYPE='FRAME' AND m.RCS_TYPE='cell'
  AND m.FRAME_ID IN (1, 2, 3, 91, 92)
  AND keep.code IS NULL;

-- 同一 RCS_CODE 多条活动：留最小 ID1
UPDATE MAS_AUTO_LOCATION_MAP m
JOIN (
  SELECT RCS_CODE, MIN(ID1) AS keep_id
  FROM MAS_AUTO_LOCATION_MAP
  WHERE STATE='0'
  GROUP BY RCS_CODE
  HAVING COUNT(*) > 1
) d ON d.RCS_CODE = m.RCS_CODE
SET m.STATE='1'
WHERE m.STATE='0' AND m.ID1 <> d.keep_id;

DELETE FROM MAS_AUTO_FRAME_SLOT WHERE FRAME_ID IN (1, 2, 3, 91, 92);

INSERT INTO MAS_AUTO_FRAME_SLOT
  (FRAME_ID, SLOT_NO, LAYER_NO, POS_IN_LAYER, SLOT_STATE, ELECTRODE_ID, BIND_SOURCE, BIND_TIME)
SELECT
  f.id,
  (l.n - 1) * 2 + p.n,
  l.n,
  p.n,
  CASE WHEN f.id = 1 THEN '1' ELSE '0' END,
  CASE WHEN f.id = 1 THEN CONCAT('101', l.n, LPAD(p.n, 2, '0')) ELSE NULL END,
  CASE WHEN f.id = 1 THEN 'MANUAL' ELSE NULL END,
  CASE WHEN f.id = 1 THEN NOW() ELSE NULL END
FROM (SELECT 1 AS id UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 91 UNION ALL SELECT 92) f
CROSS JOIN (
  SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
  UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
) l
CROSS JOIN (SELECT 1 n UNION ALL SELECT 2) p;

INSERT INTO MAS_AUTO_LOCATION_MAP (LOC_TYPE, FRAME_ID, LOC_NAME, RCS_CODE, RCS_TYPE, STATE, AUTHOR)
SELECT v.LOC_TYPE, v.FRAME_ID, v.LOC_NAME, v.RCS_CODE, v.RCS_TYPE, '0', 'system'
FROM (
  SELECT 'FRAME' LOC_TYPE, 1 FRAME_ID, '上料架101' LOC_NAME, '101' RCS_CODE, 'shelf' RCS_TYPE
  UNION ALL SELECT 'FRAME', 2,  '中转架301', '301', 'shelf'
  UNION ALL SELECT 'FRAME', 3,  '下料总架303', '303', 'shelf'
  UNION ALL SELECT 'FRAME', 91, 'NG架401',  '401', 'shelf'
  UNION ALL SELECT 'FRAME', 92, '中转架302', '302', 'shelf'
) v
WHERE NOT EXISTS (
  SELECT 1 FROM MAS_AUTO_LOCATION_MAP m
  WHERE m.RCS_CODE = v.RCS_CODE AND m.STATE = '0'
);

INSERT INTO MAS_AUTO_LOCATION_MAP (LOC_TYPE, FRAME_ID, LOC_NAME, RCS_CODE, RCS_TYPE, STATE, AUTHOR)
SELECT 'FRAME', f.id, CONCAT('L', l.n, 'P', p.n), CONCAT(f.code, l.n, LPAD(p.n, 2, '0')), 'cell', '0', 'system'
FROM (
  SELECT 1 AS id, '101' AS code
  UNION ALL SELECT 2, '301'
  UNION ALL SELECT 3, '303'
  UNION ALL SELECT 91, '401'
  UNION ALL SELECT 92, '302'
) f
CROSS JOIN (
  SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
  UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
) l
CROSS JOIN (SELECT 1 n UNION ALL SELECT 2) p
WHERE NOT EXISTS (
  SELECT 1 FROM MAS_AUTO_LOCATION_MAP m
  WHERE m.RCS_CODE = CONCAT(f.code, l.n, LPAD(p.n, 2, '0')) AND m.STATE = '0'
);

UPDATE MAS_AUTO_LOCATION_MAP
SET RCS_CODE='201101'
WHERE LOC_TYPE='POSITION' AND EQUIMENT_ID=1 AND POSITION_ID=1 AND STATE='0';
UPDATE MAS_AUTO_LOCATION_MAP
SET RCS_CODE='201102'
WHERE LOC_TYPE='POSITION' AND EQUIMENT_ID=1 AND POSITION_ID=2 AND STATE='0';

-- FRAME cell 备注名扣成 L层P位（可重复）
UPDATE MAS_AUTO_LOCATION_MAP m
JOIN MAS_AUTO_FRAME f ON f.ID1 = m.FRAME_ID AND f.STATE = '0'
SET m.LOC_NAME = CONCAT(
  'L', CAST(SUBSTRING(m.RCS_CODE, CHAR_LENGTH(f.FRAME_CODE) + 1,
        CHAR_LENGTH(m.RCS_CODE) - CHAR_LENGTH(f.FRAME_CODE) - 2) AS UNSIGNED),
  'P', CAST(RIGHT(m.RCS_CODE, 2) AS UNSIGNED))
WHERE m.STATE = '0' AND m.LOC_TYPE = 'FRAME' AND m.RCS_TYPE = 'cell'
  AND m.RCS_CODE LIKE CONCAT(f.FRAME_CODE, '%')
  AND CHAR_LENGTH(m.RCS_CODE) >= CHAR_LENGTH(f.FRAME_CODE) + 3;

SELECT ID1, FRAME_NAME, FRAME_CODE, LAYER_TOTAL, SLOTS_PER_LAYER, SLOT_TOTAL
FROM MAS_AUTO_FRAME WHERE STATE='0' ORDER BY ID1;

SELECT FRAME_ID, COUNT(*) slots, SUM(SLOT_STATE='1') occupied
FROM MAS_AUTO_FRAME_SLOT GROUP BY FRAME_ID ORDER BY FRAME_ID;

SELECT FRAME_ID, RCS_TYPE, COUNT(*) c
FROM MAS_AUTO_LOCATION_MAP
WHERE STATE='0' AND LOC_TYPE='FRAME'
GROUP BY FRAME_ID, RCS_TYPE
ORDER BY FRAME_ID, RCS_TYPE;
